import os

# Configuration variables
SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = False
# SECRET_KEY = os.getenv('SECRET_KEY')
SECRET_KEY =  os.getenv('SECRET_KEY')